  exporters:
    otlphttp/dynatrace:
      endpoint: "${env:DT_ENDPOINT_UC15}/api/v2/otlp"
      headers:
        Authorization: "Api-Token ${env:DT_API_TOKEN_UC15}"
    
  processors:
    transform:
      metric_statements:
        - context: metric
          statements:
            # Get count from the histogram. The new metric name will be <histogram_name>_count
            - extract_count_metric(true) where type == METRIC_DATA_TYPE_HISTOGRAM

            # Get sum from the histogram. The new metric name will be <histogram_name>_sum
            - extract_sum_metric(true) where type == METRIC_DATA_TYPE_HISTOGRAM
        - context: datapoint
          statements:
            # convert the <histogram_name>_sum metrics to gauges.
            - convert_sum_to_gauge() where IsMatch(metric.name, ".*_sum")
    filter:
      error_mode: ignore
      metrics:
        metric:
          - 'type == METRIC_DATA_TYPE_HISTOGRAM'
          - 'type == METRIC_DATA_TYPE_SUMMARY'
    cumulativetodelta:


    # k8sattributes:
    #   auth_type: "serviceAccount"
    #   passthrough: false
    
    #   extract:
    #     metadata:
    #       - k8s.pod.name
    #       - k8s.pod.uid
    #       - k8s.deployment.name
    #       - k8s.statefulset.name
    #       - k8s.daemonset.name
    #       - k8s.cronjob.name
    #       - k8s.namespace.name
    #       - k8s.node.name
    #       - k8s.cluster.uid
    #   pod_association:
    #     - sources:
    #       - from: resource_attribute
    #         name: k8s.pod.name
    #       - from: resource_attribute
    #         name: k8s.namespace.name
    #     # Pod labels which can be fetched via K8sattributeprocessor

  service:
    pipelines:
      traces:
        # processors: [k8sattributes]
        exporters: [spanmetrics, otlphttp/dynatrace]
      logs:
        # processors: [k8sattributes]
        exporters: [otlphttp/dynatrace]
      metrics:
        processors: [transform, filter, cumulativetodelta]
        # processors: [transform, filter, k8sattributes, cumulativetodelta]
        exporters: [otlphttp/dynatrace]